// Generated by Avo. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.
//
// App B's source-specific file: events, enums, system properties, and config
// generated from App B's Avo source. Note that App B's surface is completely
// different from App A's — its own events, its own AppBPlan enum, its own
// system properties, and a different destination set (no mixpanel).
//
// NOTE: this example plan was generated into package `com.avodemo.appb.avo`
// (instead of the default `sh.avo`) so a shell app can depend on both App A's
// and App B's generated code without class name collisions.
@file:Suppress("unused", "LiftReturnOrAssignment", "FunctionName", "UnusedImport",
"ObjectPropertyName", "SameParameterValue", "UnnecessaryVariable", "UNUSED_PARAMETER",
"UNUSED_VARIABLE", "LocalVariableName", "DEPRECATION", "UsePropertyAccessSyntax",
"PrivatePropertyName", "PrivatePropertyName", "CascadeIf", "MemberVisibilityCanBePrivate",
"SpellCheckingInspection", "EnumEntryName", "MaximumLineLength")
package com.avodemo.appb.avo

import sh.avo.*

object AvoTypes {
    enum class AppBPlan(val underlying: String) {
        FREE("Free"),
        PRO("Pro"),
        ENTERPRISE("Enterprise"),
        TRIAL("Trial")
    }
}

object AppSystemProperties {
    @Volatile private var _configured = false
    val isConfigured: Boolean
        @Synchronized get() {
        return _configured
    }

    private var _tenantId: String? = null
    private var _betaFeaturesEnabled: Boolean? = null

    @Synchronized fun configure(
        tenantId: String,
        betaFeaturesEnabled: Boolean
    ) {
        _tenantId = tenantId
        _betaFeaturesEnabled = betaFeaturesEnabled
        _configured = true
    }

    @Synchronized fun toMap(): Map<String, Any> {
        if (!_configured) {
            println("[avo] Warning: AppSystemProperties.configure() has not been called. System properties will be omitted.")
            return emptyMap()
        }
        val props = mutableMapOf<String, Any>()
        _tenantId?.let {
            props["Tenant Id"] = it
        }
         ?: run {
            println("[avo] Warning: Required system property 'Tenant Id' was not set. Call AppSystemProperties.configure() with this property.")
        }
        _betaFeaturesEnabled?.let {
            props["Beta Features Enabled"] = it
        }
         ?: run {
            println("[avo] Warning: Required system property 'Beta Features Enabled' was not set. Call AppSystemProperties.configure() with this property.")
        }
        return props
    }

    @Synchronized fun collectViolations(): List<AvoAssertMessage> {
        val messages = mutableListOf<AvoAssertMessage>()

        return messages
    }
}

object AppBSignOutEvent : AvoEvent {
    override val eventId = "bBsignOut"
    override val eventHash = "5d8b2f1a4c7e0d3b6f9a2c5e8d1b4f7a0c3e6d9b2f5a8c1e4d7b0f3a6c9e2d5b"
    override val eventName = "App B Sign Out"

    override fun buildBaseProperties(): Map<String, Any> {
        val eventProperties = mutableMapOf<String, Any>()

        for ((key, value) in AppSystemProperties.toMap()) {
            eventProperties[key] = value
        }
        return eventProperties
    }

    override val properties: Map<String, AvoDestinationEvent>
    get() {
        val eventProperties = buildBaseProperties()

        return mapOf(
            "segment" to AvoDestinationEvent(name = "App B Sign Out", properties = eventProperties),
            "amplitude" to AvoDestinationEvent(name = "App B Sign Out", properties = eventProperties),
            "customDest" to AvoDestinationEvent(name = "App B Sign Out", properties = eventProperties)
        )
    }

    override fun collectViolations(): List<AvoAssertMessage> {
        val messages = mutableListOf<AvoAssertMessage>()
        messages.addAll(AppSystemProperties.collectViolations())

        return messages
    }

    override fun verify(): AvoResult<Unit, AvoVerificationError> {
        if (!AppSystemProperties.isConfigured) {
            return AvoResult.Failure(AvoVerificationError(listOf("AppSystemProperties.configure() must be called before sending events.")))
        }
        val violations = collectViolations()
        return if (violations.isEmpty()) {
            AvoResult.Success(Unit)
        } else {
            AvoResult.Failure(AvoVerificationError(violations.map { it.message }))
        }
    }
}

data class AppBPlanSelectedEvent(val plan: AvoTypes.AppBPlan,
    val seatCount: Int,
    val discountPercent: Double?) : AvoEvent {
    override val eventId = "bBplanSel"
    override val eventHash = "9a3c6e0b2d5f8a1c4e7b0d3f6a9c2e5b8d1f4a7c0e3b6d9f2a5c8e1b4d7f0a3c"
    override val eventName = "App B Plan Selected"

    override fun buildBaseProperties(): Map<String, Any> {
        val eventProperties = mutableMapOf<String, Any>()
        eventProperties["Plan"] = plan.underlying
        eventProperties["Seat Count"] = seatCount
        discountPercent?.let {
            eventProperties["Discount Percent"] = it
        }

        for ((key, value) in AppSystemProperties.toMap()) {
            eventProperties[key] = value
        }
        return eventProperties
    }

    override val properties: Map<String, AvoDestinationEvent>
    get() {
        val eventProperties = buildBaseProperties()

        // Segment destination: event name remapped
        return mapOf(
            "segment" to AvoDestinationEvent(name = "app_b_plan_selected", properties = eventProperties),
            "amplitude" to AvoDestinationEvent(name = "App B Plan Selected", properties = eventProperties),
            "customDest" to AvoDestinationEvent(name = "App B Plan Selected", properties = eventProperties)
        )
    }

    override fun collectViolations(): List<AvoAssertMessage> {
        val messages = mutableListOf<AvoAssertMessage>()
        messages.addAll(AppSystemProperties.collectViolations())
        messages.addAll(AvoAssert.assertMin("rM4yWaB2c", "Seat Count", min=1, value=seatCount))
        discountPercent?.let { discountPercent ->
            messages.addAll(AvoAssert.assertMin("rM4yWaB2d", "Discount Percent", min=0.000000, value=discountPercent))
            messages.addAll(AvoAssert.assertMax("rM4yWaB2d", "Discount Percent", max=100.000000, value=discountPercent))
        }

        return messages
    }

    override fun verify(): AvoResult<Unit, AvoVerificationError> {
        if (!AppSystemProperties.isConfigured) {
            return AvoResult.Failure(AvoVerificationError(listOf("AppSystemProperties.configure() must be called before sending events.")))
        }
        val violations = collectViolations()
        return if (violations.isEmpty()) {
            AvoResult.Success(Unit)
        } else {
            AvoResult.Failure(AvoVerificationError(violations.map { it.message }))
        }
    }
}

object AvoTrackingPlanConfig {
    val config = AvoInvokeConfig(
        actionId = "REPLACE_WITH_APP_B_ACTION_ID",
        branchId = "master",
        schemaId = "REPLACE_WITH_APP_B_SCHEMA_ID",
        sourceId = "REPLACE_WITH_APP_B_SOURCE_ID",
        inspectorApiKey = null
    )
}


fun Avo.Companion.initAvo(
    env: AvoEnv,
    tenantId: String,
    betaFeaturesEnabled: Boolean,
    inspector: Any? = null,
    strict: Boolean = true,
    noop: Boolean = false
): Avo {
    AppSystemProperties.configure(
        tenantId = tenantId,
        betaFeaturesEnabled = betaFeaturesEnabled
    )
    return Avo(env = env, config = AvoTrackingPlanConfig.config, inspector = inspector, strict = strict, noop = noop)
}
