// Generated by Avo. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import type { AvoCodegenConfig } from './AvoLibrary';

export type DestinationKey = "Segment" | "Amplitude" | "Mixpanel" | "Snowplow" | "FacebookAnalytics" | "CustomDest";


// Codegen-bound configuration. Embedded by 'avo pull' — do not edit manually.
// Move this file (and the import path) to wherever in your layout you want
// Avo.init to live: at the app level, library level, or any module boundary.
//
// EXPORTED AS DEFAULT so a shell host that bundles multiple apps can import
// each app's config without name aliasing:
//   import appAConfig from './apps/a/AvoConfig';
//   import appBConfig from './apps/b/AvoConfig';
// Single-app callers (no shell): import appConfig from './AvoConfig';
const codegenConfig: AvoCodegenConfig = {
  invokeConfig: {
    schemaId: "REPLACE_WITH_YOUR_SCHEMA_ID",
    actionId: "REPLACE_WITH_YOUR_ACTION_ID",
    branchId: "master",
    sourceId: "REPLACE_WITH_YOUR_SOURCE_ID",
    inspectorApiKey: "REPLACE_WITH_YOUR_INSPECTOR_API_KEY",
  },
  requiredDestinationKeys: ["Segment", "Amplitude", "Mixpanel", "Snowplow", "FacebookAnalytics", "CustomDest"],
  destinationApiKeys: {
    "Segment": { prod: "REPLACE_WITH_SEGMENT_API_KEY", dev: "REPLACE_WITH_SEGMENT_API_KEY", staging: "REPLACE_WITH_SEGMENT_API_KEY" },
    "Amplitude": { prod: "REPLACE_WITH_AMPLITUDE_API_KEY", dev: "REPLACE_WITH_AMPLITUDE_API_KEY" },
    "Mixpanel": { prod: "REPLACE_WITH_MIXPANEL_API_KEY", dev: "REPLACE_WITH_MIXPANEL_API_KEY" },
    "Snowplow": { prod: "0000", dev: "0000" },
    "FacebookAnalytics": { prod: "REPLACE_WITH_FACEBOOK_API_KEY_PROD", dev: "REPLACE_WITH_FACEBOOK_API_KEY_DEV" },
    "CustomDest": { prod: null, dev: null },
  },
};
export default codegenConfig;

