// Generated by Avo. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck

export enum AvoEnv {
  Prod = "prod",
  Staging = "staging",
  Dev = "dev",
}

export interface AvoAssertMessage {
  tag: string;
  propertyId: string;
  message: string;
  actualType?: string;
  getMessage(): string;
}

export const AvoAssert = {
  safeStringify(value: unknown): string {
    try {
      return JSON.stringify(value);
    } catch {
      return "[unserializable]";
    }
  },
  assertObject: function assertObject(propertyId: string, propName: string, obj: any): AvoAssertMessage[] {
    if (obj === null || Array.isArray(obj) || typeof obj !== 'object') {
      const actualType = obj === null ? 'null' : Array.isArray(obj) ? 'array' : typeof obj;
      const message = propName + ' should be of type object but you provided type ' + actualType + ' with value ' + AvoAssert.safeStringify(obj);
      return [{ tag: 'expectedObjectType', propertyId, message, actualType, getMessage() { return message; } }];
    }
    return [];
  },
  assertString: function assertString(propertyId: string, propName: string, str: any): AvoAssertMessage[] {
    if (typeof str !== 'string') {
      const message = propName + ' should be of type string but you provided type ' + typeof str + ' with value ' + AvoAssert.safeStringify(str);
      return [{ tag: 'expectedStringType', propertyId, message, actualType: typeof str, getMessage() { return message; } }];
    }
    return [];
  },
  assertInt: function assertInt(propertyId: string, propName: string, int: any): AvoAssertMessage[] {
    if (typeof int === 'number' && int !== Math.round(int)) {
      const message = propName + ' should be of type int but you provided type float with value ' + AvoAssert.safeStringify(int);
      return [{ tag: 'expectedIntType', propertyId, message, actualType: 'float', getMessage() { return message; } }];
    } else if (typeof int !== 'number') {
      const message = propName + ' should be of type int but you provided type ' + typeof int + ' with value ' + AvoAssert.safeStringify(int);
      return [{ tag: 'expectedIntType', propertyId, message, actualType: typeof int, getMessage() { return message; } }];
    }
    return [];
  },
  assertFloat: function assertFloat(propertyId: string, propName: string, float: any): AvoAssertMessage[] {
    if (typeof float !== 'number') {
      const message = propName + ' should be of type float but you provided type ' + typeof float + ' with value ' + AvoAssert.safeStringify(float);
      return [{ tag: 'expectedFloatType', propertyId, message, actualType: typeof float, getMessage() { return message; } }];
    }
    return [];
  },
  assertBool: function assertBool(propertyId: string, propName: string, bool: any): AvoAssertMessage[] {
    if (typeof bool !== 'boolean') {
      const message = propName + ' should be of type boolean but you provided type ' + typeof bool + ' with value ' + AvoAssert.safeStringify(bool);
      return [{ tag: 'expectedBoolType', propertyId, message, actualType: typeof bool, getMessage() { return message; } }];
    }
    return [];
  },
  assertMax: function assertMax(propertyId: string, propName: string, max: number, value: any): AvoAssertMessage[] {
    if (typeof value === 'number' && value > max) {
      const message = propName + ' should be at most ' + max + ' but you provided ' + value;
      return [{ tag: 'expectedMax', propertyId, message, getMessage() { return message; } }];
    }
    return [];
  },
  assertMin: function assertMin(propertyId: string, propName: string, min: number, value: any): AvoAssertMessage[] {
    if (typeof value === 'number' && value < min) {
      const message = propName + ' should be at least ' + min + ' but you provided ' + value;
      return [{ tag: 'expectedMin', propertyId, message, getMessage() { return message; } }];
    }
    return [];
  },
  assertList: function assertList(propertyId: string, propName: string, value: any): AvoAssertMessage[] {
    if (!Array.isArray(value)) {
      const message = propName + ' should be a list but you provided ' + typeof value;
      return [{ tag: 'expectedList', propertyId, message, getMessage() { return message; } }];
    }
    return [];
  },
};

export interface AvoInvokeConfig {
  readonly schemaId: string;
  readonly actionId: string;
  readonly branchId: string;
  readonly sourceId: string;
  readonly env: AvoEnv;
  readonly inspectorApiKey?: string;
}

// Per-instance sampling state. Each Avo instance owns one of these and passes
// it to AvoInvoke.invoke / invokeMeta. The server's response (data.sa) mutates
// state.rate so the next call's sampling decision uses the latest server value.
export interface AvoSamplingState {
  rate: number;
}

// AvoInvoke: config-parameterized invocation metrics.
// invoke() and invokeMeta() accept an AvoInvokeConfig so the caller
// supplies IDs at runtime rather than having them hardcoded here.
// Mirrors AvoSwift.res printInvocationFunctionWithConfig.
export const AvoInvoke = {
  invoke(eventId: string, eventHash: string, violations: AvoAssertMessage[], config: AvoInvokeConfig, samplingState: AvoSamplingState): void {
    if (samplingState.rate <= 0) { return; }
    if (Math.random() >= samplingState.rate) { return; }
    try {
      fetch("https://api.avo.app/i", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          "ac": config.actionId,
          "br": config.branchId,
          "sc": config.schemaId,
          "so": config.sourceId,
          "en": config.env,
          "ev": eventId,
          "ha": eventHash,
          "se": (new Date()).toISOString(),
          "va": violations.length === 0,
          "me": violations,
          "or": "library-interface"
        })
      }).then((res: any) => res.json()).then((data: any) => {
        const nextSamplingRate = data?.sa;
        if (typeof nextSamplingRate === "number" && Number.isFinite(nextSamplingRate) && nextSamplingRate >= 0 && nextSamplingRate <= 1) {
          samplingState.rate = nextSamplingRate;
        }
      }).catch(() => {});
    } catch (_e) {}
  },

  invokeMeta(type: string, messages: AvoAssertMessage[], config: AvoInvokeConfig, samplingState: AvoSamplingState): void {
    if (samplingState.rate <= 0) { return; }
    if (Math.random() >= samplingState.rate) { return; }
    try {
      fetch("https://api.avo.app/i", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          "ac": config.actionId,
          "br": config.branchId,
          "sc": config.schemaId,
          "so": config.sourceId,
          "en": config.env,
          "ty": type,
          "se": (new Date()).toISOString(),
          "va": messages.length === 0,
          "me": messages,
          "or": "library-interface"
        })
      }).then((res: any) => res.json()).then((data: any) => {
        const nextSamplingRate = data?.sa;
        if (typeof nextSamplingRate === "number" && Number.isFinite(nextSamplingRate) && nextSamplingRate >= 0 && nextSamplingRate <= 1) {
          samplingState.rate = nextSamplingRate;
        }
      }).catch(() => {});
    } catch (_e) {}
  },
};

export interface AvoInspector {
  avoFunctionTrackSchemaFromEvent(eventName: string, eventParams: Record<string, unknown>): void;
}

export interface AvoDestinationEvent {
  readonly name: string;
  readonly properties: Record<string, unknown>;
}

export interface AvoEvent {
  readonly eventId: string;
  readonly eventHash: string;
  readonly eventName: string;
  readonly properties: Record<string, AvoDestinationEvent>;
  buildBaseProperties(): Record<string, unknown>;
  readonly canonicalProperties: Record<string, unknown>;
  collectViolations(): AvoAssertMessage[];
  /** runValidation() is the hook track() uses. Subclasses override it to add pre-checks
   *  (e.g. AppSystemProperties.isConfigured) BEFORE collectViolations() runs. */
  runValidation(): AvoAssertMessage[];
  verify(): void;
}

export interface AvoDestinationLogEvent {
  /** Destination-specific (mapped) name for this event. */
  readonly name: string;
  /** Flattened event properties for this destination. */
  readonly properties: Record<string, unknown>;
  readonly eventId: string;
  readonly eventHash: string;
  /** Canonical Avo display name, used for inspector/identity correlation. */
  readonly eventName: string;
}

export interface AvoDestination {
  make(env: AvoEnv, apiKey?: string): void;
  logEvent(event: AvoDestinationLogEvent): void;
  setUserProperties(userId: string, properties: Record<string, unknown>): void;
}

// Runtime AvoConfig — the shape callers pass to Avo.init() at runtime.
// destinations is OPTIONAL: omit (or pass {}) to opt out of internal fan-out and
// have track() simply return the per-destination payload map for caller-side fan-out.
// When populated, it must cover all required destination keys (all-or-nothing).
export interface AvoConfig {
  readonly env: AvoEnv;
  readonly inspector?: AvoInspector | null;
  /** Defaults to false. When true, track() throws AvoVerificationError on validation failures in non-prod envs. */
  readonly strict?: boolean;
  readonly noop?: boolean;
  readonly destinations?: Partial<Record<string, AvoDestination>>;
}

// Codegen-bound configuration. Embedded by 'avo pull' into AvoConfig.ts and
// passed to Avo.init(config, codegenConfig) by the caller. Plan-specific data —
// callers do not construct this directly.
export interface AvoCodegenConfig {
  readonly invokeConfig: AvoInvokeConfig;
  readonly requiredDestinationKeys: string[];
  readonly destinationApiKeys: Record<string, { prod: string | null; dev: string | null; staging?: string | null }>;
}

export class AvoVerificationError extends Error {
  public readonly messages: string[];
  constructor(messages: string[]) {
    super(messages.join("; "));
    // Restore prototype chain immediately after super() — required for correct instanceof checks
    // when TypeScript targets ES5 (transpiled classes lose the prototype chain otherwise).
    Object.setPrototypeOf(this, AvoVerificationError.prototype);
    this.name = "AvoVerificationError";
    this.messages = messages;
    // Capture a clean stack trace when V8 is available (Node.js / Chrome).
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, AvoVerificationError);
    }
  }
}

// BaseAvoEvent: abstract class providing default implementations for AvoEvent.
// This is the TypeScript analog of Swift's protocol extension defaults.
// Concrete event classes extend BaseAvoEvent and override what they need.
export abstract class BaseAvoEvent implements AvoEvent {
  abstract readonly eventId: string;
  abstract readonly eventHash: string;
  abstract readonly eventName: string;
  abstract readonly properties: Record<string, AvoDestinationEvent>;
  abstract buildBaseProperties(): Record<string, unknown>;

  get canonicalProperties(): Record<string, unknown> {
    return this.buildBaseProperties();
  }

  collectViolations(): AvoAssertMessage[] {
    return [];
  }

  /** runValidation() is what track() calls. Override in subclasses to add pre-checks
   *  (e.g. AppSystemProperties.isConfigured) before collectViolations() runs.
   *  The default implementation just returns collectViolations(). */
  runValidation(): AvoAssertMessage[] {
    return this.collectViolations();
  }

  verify(): void {
    const messages = this.runValidation();
    if (messages.length > 0) {
      throw new AvoVerificationError(messages.map(v => v.getMessage()));
    }
  }
}

// The Avo runtime class. Plan-agnostic — all plan-specific data (invokeConfig, required
// destination keys, per-destination api keys) flows in via the AvoCodegenConfig argument
// to init(). One Avo instance per app — multi-app shells construct multiple instances
// and each owns its own samplingState (no module-global sampling state).
export class Avo {
  private readonly env: AvoEnv;
  private readonly strict: boolean;
  private readonly noop: boolean;
  private readonly inspector?: AvoInspector | null;
  private readonly destinations: Record<string, AvoDestination>;
  private readonly invokeConfig: AvoInvokeConfig;
  // Per-instance sampling state — mutated by AvoInvoke based on server response.
  // Each Avo.init() returns a separate instance with its own state, so multi-app
  // shells do not share a single sampling decision across plans.
  private readonly samplingState: AvoSamplingState = { rate: 1.0 };

  private constructor(config: AvoConfig, invokeConfig: AvoInvokeConfig, resolvedDestinations: Record<string, AvoDestination>) {
    this.env = config.env;
    this.strict = config.strict ?? false;
    this.noop = config.noop ?? false;
    this.inspector = config.inspector;
    this.destinations = resolvedDestinations;
    this.invokeConfig = invokeConfig;

    // Part B: noop warn — TS deliberately does NOT force noop=false in prod (diverges from Swift)
    if (config.noop === true) {
      console.warn("[avo] noop mode is active — all track() calls will be no-ops.");
    }
    if (!this.noop && this.env !== AvoEnv.Prod) {
      AvoInvoke.invokeMeta("init", [], this.invokeConfig, this.samplingState);
    }
  }

  // init resolves destinations against the codegen-bound requiredDestinationKeys list,
  // then calls make() on each resolved destination, then constructs the Avo instance.
  // Resolution policy:
  //   Branch (1) zero-destination plan      → resolved = {}, no fan-out
  //   Branch (2) no destinations provided   → resolved = {}, no fan-out (matches Swift/Kotlin process())
  //   Branch (3) partial destinations       → throw (all-or-nothing)
  //   Branch (4) full destinations          → resolved = provided
  static init(config: AvoConfig, codegenConfig: AvoCodegenConfig): Avo {
    const required = codegenConfig.requiredDestinationKeys;
    const provided = config.destinations ?? {};
    const providedKeys = Object.keys(provided);

    let resolved: Record<string, AvoDestination>;

    if (required.length === 0) {
      // Branch (1): zero-destination plan. Resolved is empty regardless of what was provided.
      resolved = {};
    } else if (providedKeys.length === 0) {
      // Branch (2): no destinations provided — opt out of internal fan-out.
      // track() still returns the per-destination payload map; caller fans out.
      resolved = {};
    } else if (providedKeys.length < required.length) {
      // Branch (3): partial. Caller probably forgot to add a destination after pulling. Fail fast.
      const missing = required.filter(k => !(k in provided));
      throw new Error(
        `[avo] Avo.init: custom destinations must cover all DestinationKeys (all-or-nothing). Missing: [${missing.join(", ")}]. Provide implementations for all DestinationKeys.`
      );
    } else {
      // Branch (4): full custom destinations.
      const missing = required.filter(k => !(k in provided));
      if (missing.length > 0) {
        throw new Error(
          `[avo] Avo.init: custom destinations must cover all DestinationKeys (all-or-nothing). Missing: [${missing.join(", ")}]. Provide implementations for all DestinationKeys.`
        );
      }
      resolved = provided as Record<string, AvoDestination>;
    }

    // Call make() on each resolved destination. Skip the loop when resolved is empty
    // (zero-destination plan or opted-out caller). Per-destination try/catch ensures
    // one misbehaving destination does not prevent others from initializing.
    for (const [key, dest] of Object.entries(resolved)) {
      try {
        const keys = codegenConfig.destinationApiKeys[key];
        const apiKey = keys
          ? (config.env === AvoEnv.Prod ? keys.prod : config.env === AvoEnv.Staging ? (keys.staging ?? keys.dev) : keys.dev)
          : undefined;
        dest.make(config.env, apiKey ?? undefined);
      } catch (e) {
        console.warn("[avo] Destination " + key + " make() threw, continuing", e);
      }
    }

    // Merge env into invokeConfig at runtime so invocation metrics carry the environment dimension.
    const invokeConfig = { ...codegenConfig.invokeConfig, env: config.env };
    return new Avo(config, invokeConfig, resolved);
  }

  // track returns the per-destination payload map (event.properties). Callers may use
  // the return value to fan out manually to their own SDKs (Swift/Kotlin process()
  // semantics). When this.destinations is non-empty the lib also fans out internally
  // by calling each dest.logEvent — both behaviors layer cleanly.
  track(event: AvoEvent): Record<string, AvoDestinationEvent> {
    if (this.noop) { return event.properties; }

    // Call runValidation() instead of collectViolations() directly so that per-event
    // overrides (e.g. the AppSystemProperties.isConfigured pre-check) run in the
    // production tracking path — not just when verify() is called explicitly.
    let violations: AvoAssertMessage[];
    try {
      violations = event.runValidation();
    } catch (e) {
      if (e instanceof AvoVerificationError) {
        if (this.env !== AvoEnv.Prod && this.strict) {
          throw e;
        } else {
          for (const msg of e.messages) {
            console.error("[avo] Pre-validation check failed: " + msg);
          }
        }
        return event.properties; // do not fan-out when pre-validation throws, but still return the map
      }
      throw e;
    }
    if (this.env !== AvoEnv.Prod) {
      AvoInvoke.invoke(event.eventId, event.eventHash, violations, this.invokeConfig, this.samplingState);
    }

    if (violations.length > 0) {
      if (this.env !== AvoEnv.Prod && this.strict) {
        throw new AvoVerificationError(violations.map(v => v.getMessage()));
      } else {
        for (const v of violations) {
          console.error("[avo] Verification failed: " + v.getMessage());
        }
        // continue to inspector + fan-out
      }
    }

    if (this.inspector != null) {
      try {
        const inspectorProperties: Record<string, unknown> = { ...event.canonicalProperties };
        inspectorProperties["avoFunctionEventId"] = event.eventId;
        inspectorProperties["avoFunctionEventHash"] = event.eventHash;
        this.inspector.avoFunctionTrackSchemaFromEvent(event.eventName, inspectorProperties);
      } catch (e) {
        console.error("[avo] Inspector call failed: " + e);
      }
    }

    // Internal fan-out — only when destinations is non-empty. Caller can opt out by
    // omitting destinations from config; track() return value still carries the map
    // so the caller can fan out manually.
    if (Object.keys(this.destinations).length > 0) {
      for (const [key, dest] of Object.entries(this.destinations)) {
        const payload = (event.properties as Record<string, AvoDestinationEvent>)[key];
        if (payload) {
          try {
            dest.logEvent({
              name: payload.name,
              properties: payload.properties,
              eventId: event.eventId,
              eventHash: event.eventHash,
              eventName: event.eventName,
            });
          } catch (e) { console.warn("[avo] Destination " + key + " logEvent threw, continuing", e); }
        }
      }
    }

    return event.properties;
  }

  // setUserProperties is a no-op when destinations is empty. Callers in no-destinations
  // mode call their own SDKs' identify/setUserProperties directly. No payload-map return —
  // user properties are flat (no per-destination payload structure).
  setUserProperties(userId: string, properties: Record<string, unknown>): void {
    if (this.noop) { return; }
    if (Object.keys(this.destinations).length === 0) { return; }
    for (const [key, dest] of Object.entries(this.destinations)) {
      try {
        dest.setUserProperties(userId, { ...properties });
      } catch (e) {
        console.warn("[avo] Destination " + key + " setUserProperties threw, continuing", e);
      }
    }
  }
}
