// swiftlint:disable all
// Generated by Avo VERSION 222.0.0. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.

// ============================================================================
// APP LAYER — App-specific event structs
// ============================================================================
// This file lives in the app target (e.g., Cooking, News).
// It contains concrete event structs conforming to the AvoEvent protocol
// defined in the library layer.
//
// Each struct:
// - Has typed properties matching the event schema
// - Implements `properties` returning per-destination AvoEventOut
//   (with name mapping, pinned properties, AND system properties applied)
// - Implements `verify()` with schema validation rules
//
// SYSTEM PROPERTIES: Different apps can have different system properties.
// System properties are defined at the app level and included in each event
// struct's `properties` getter. The app sets system property values once
// (e.g., at startup) and each event includes them. See AppSystemProperties
// below for how this works.
//
// FEATURE REQUEST: "Typed Codegen Data Structures" [BLOCKER]
// These structs ARE the typed data structures. Instead of a global Avo.track()
// callback that routes internally, each event is a standalone struct.
// The developer creates the struct, inspects it, verifies it, and extracts
// its typed properties — full control, full visibility.
//
// FEATURE REQUEST: "Event Verify Method in Codegen" [Must Have]
// Each struct below implements verify() with its specific validation rules.
// verify() accumulates ALL violations (does not short-circuit on first failure),
// throws AvoVerificationError with the full list of violation messages.
//
// FEATURE REQUEST: "Automated JSON Key Formatting" [Must Have]
// The `properties` computed property below shows how name mapping works:
// - Global mapping: "GLOBAL_NAME_MAPPING_ALL" replaces the original key for all destinations
// - Per-destination mapping: "GLOBAL_NAME_MAPPING_ONE" only for analyticsDest
// - Pinned properties: constant values added at generation time, not passed by the developer
// ============================================================================

import Foundation

// MARK: - AvoTypes (App-Specific)

// These types are generated per-app — each app (Cooking, News, etc.) gets its own
// set of enums and object structs matching its event schemas. They live HERE in the
// app layer, not in the shared library, because different apps have different:
// - Event property allowed values
// - System property types
// - Object property structures
public enum AvoTypes {
    public enum RequiredStringEventProperty : String, Sendable {
        case beer = "beer"
        case wine = "wine"
        case cocktail = "cocktail"
        case water = "water"
    }

    public enum OptionalStringEventProperty : String, Sendable {
        case lamp = "lamp"
        case book = "book"
        case head = "head"
        case floor = "floor"
    }

    public enum RequiredStringSystemProperty : String, Sendable {
        case web = "Web"
        case iOS = "iOS"
        case android = "Android"
        case server = "Server"
    }

    public enum OptionalStringSystemProperty : String, Sendable {
        case sock = "Sock"
        case pants = "Pants"
    }

    // Allowed values — the type system enforces that only these values can be passed.
    // The base event uses EventPropertyWithAllowedValues, while a variant of the same
    // event uses EventPropertyWithAllowedValuesVariantI with a different set of allowed values.
    // This demonstrates how Avo governs allowed values at compile time via enums.
    public enum EventPropertyWithAllowedValues : String, Sendable {
        case eventValueI = "Event Value I"
        case valueI = "Value I"
        case valueIi = "Value II"
        case variantWithSymbol = "Variant with ' symbol"
    }

    public enum EventPropertyWithAllowedValuesVariantI : String, Sendable {
        case eventValueI = "Event Value I"
        case valueI = "Value I"
        case variantValueI = "Variant Value I"
        case variantWithSymbol = "Variant with ' symbol"
    }

    public enum RequiredListEventProperty : String, Sendable {
        case coffee = "coffee"
        case cup = "cup"
        case phone = "phone"
    }

    public enum RequiredListSystemProperty : String, Sendable {
        case pizza = "Pizza"
        case burger = "Burger"
        case pasta = "Pasta"
        case sushi = "Sushi"
    }

    public enum RequiredStringUserProperty : String, Sendable {
        case toes = "toes"
        case fingers = "fingers"
        case knee = "knee"
    }

    public enum OptionalStringUserProperty : String, Sendable {
        case calf = "calf"
        case thigh = "thigh"
        case hip = "hip"
    }

    // FEATURE REQUEST: "Complex Array Governance" [Must Have]
    // Object structs like this one demonstrate how Avo governs the key names
    // within complex nested objects. Each field is typed and validated.
    // The serialize() method produces the governed key names.
    public struct RequiredObjectEventProperty: Equatable, Sendable {
        public init(
                boolValue: Bool?,
                stringValue: String?,
                intValue: Int,
                floatValue: Double) {
            self.boolValue = boolValue
            self.stringValue = stringValue
            self.intValue = intValue
            self.floatValue = floatValue
        }
        let boolValue: Bool?
        let stringValue: String?
        let intValue: Int
        let floatValue: Double
        public func serialize() -> [String: Any] {
            var obj: [String: Any] = [:]
            if boolValue != nil {
                obj["bool_value"] = boolValue
            }
            if stringValue != nil {
                obj["string_value"] = stringValue
            }
            obj["int_value"] = intValue
            obj["float_value"] = floatValue
            return obj
        }
    }

    public struct OptionalObjectEventProperty: Equatable, Sendable {
        public init(
                intValue: [Int],
                floatValue: Double?,
                boolValue: [Bool]?,
                stringValue: String) {
            self.intValue = intValue
            self.floatValue = floatValue
            self.boolValue = boolValue
            self.stringValue = stringValue
        }
        let intValue: [Int]
        let floatValue: Double?
        let boolValue: [Bool]?
        let stringValue: String
        public func serialize() -> [String: Any] {
            var obj: [String: Any] = [:]
            obj["int_value"] = intValue
            if floatValue != nil {
                obj["float_value"] = floatValue
            }
            if boolValue != nil {
                obj["bool_value"] = boolValue
            }
            obj["string_value"] = stringValue
            return obj
        }
    }

    // FEATURE REQUEST: "Systematized Universal Properties" [Must Have]
    // System properties are app-specific — different apps can have different
    // system property types. These structs define the shape of system properties
    // for THIS app.
    public struct RequiredObjectSystemProperty: Equatable, Sendable {
        public init(
                boolValue: Bool,
                stringValue: String,
                intValue: Int,
                floatValue: Double) {
            self.boolValue = boolValue
            self.stringValue = stringValue
            self.intValue = intValue
            self.floatValue = floatValue
        }
        let boolValue: Bool
        let stringValue: String
        let intValue: Int
        let floatValue: Double
        public func serialize() -> [String: Any] {
            var obj: [String: Any] = [:]
            obj["bool_value"] = boolValue
            obj["string_value"] = stringValue
            obj["int_value"] = intValue
            obj["float_value"] = floatValue
            return obj
        }
    }

    public struct OptionalObjectSystemProperty: Equatable, Sendable {
        public init(
                boolValue: Bool,
                stringValue: String,
                intValue: Int,
                floatValue: Double) {
            self.boolValue = boolValue
            self.stringValue = stringValue
            self.intValue = intValue
            self.floatValue = floatValue
        }
        let boolValue: Bool
        let stringValue: String
        let intValue: Int
        let floatValue: Double
        public func serialize() -> [String: Any] {
            var obj: [String: Any] = [:]
            obj["bool_value"] = boolValue
            obj["string_value"] = stringValue
            obj["int_value"] = intValue
            obj["float_value"] = floatValue
            return obj
        }
    }
}

// MARK: - System Properties

// -----------------------------------------------------------------------
// FEATURE REQUEST: "Systematized Universal Properties" [Must Have]
// System properties are app-specific — different apps (Cooking, News, etc.)
// can have different system property sets. They are stored in a shared
// mutable container at the app level, set once at app startup, and
// included in every event's `properties` getter.
//
// In the original codegen, system properties were stored on the Avo actor
// and merged in send(). Now they live here because each app defines its own.
// -----------------------------------------------------------------------
// Thread-safe: all reads and writes are serialized via NSLock.
// System properties can be updated at any time (e.g., after login, locale change)
// and event property reads will always see a consistent snapshot.
public final class AppSystemProperties: @unchecked Sendable {
    public static let shared = AppSystemProperties()

    private let lock = NSLock()
    private var _requiredStringSystemProperty: AvoTypes.RequiredStringSystemProperty = .iOS
    private var _optionalStringSystemProperty: AvoTypes.OptionalStringSystemProperty? = nil
    private var _requiredIntSystemProperty: Int = 0
    private var _optionalIntSystemProperty: Int? = nil

    private init() {}

    /// Update system properties. Can be called at any time — thread-safe.
    /// Typical call sites: app startup, after login, on locale change, etc.
    public func configure(
        requiredStringSystemProperty: AvoTypes.RequiredStringSystemProperty,
        optionalStringSystemProperty: AvoTypes.OptionalStringSystemProperty?,
        requiredIntSystemProperty: Int,
        optionalIntSystemProperty: Int?
    ) {
        lock.lock()
        defer { lock.unlock() }
        _requiredStringSystemProperty = requiredStringSystemProperty
        _optionalStringSystemProperty = optionalStringSystemProperty
        _requiredIntSystemProperty = requiredIntSystemProperty
        _optionalIntSystemProperty = optionalIntSystemProperty
    }

    /// Returns system properties as a dictionary, ready to merge into event properties.
    /// Thread-safe: returns a consistent snapshot even if configure() is called concurrently.
    func toDictionary() -> [String: Any] {
        lock.lock()
        defer { lock.unlock() }
        var props: [String: Any] = [:]
        props["Required String System Property"] = _requiredStringSystemProperty.rawValue
        if let val = _optionalStringSystemProperty {
            props["Optional String System Property"] = val.rawValue
        }
        props["Required Int System Property"] = _requiredIntSystemProperty
        if let val = _optionalIntSystemProperty {
            props["Optional Int System Property"] = val
        }
        return props
    }
}

// -----------------------------------------------------------------------
// Event: Test Event With Many Event Props
// A representative event showing typed properties, validation, and enrichment.
//
// Source: Avo.swift lines 467-509 (original struct) + lines 1380-1530 (original track method)
// -----------------------------------------------------------------------
public struct TestEventWithManyEventPropsEvent: AvoEvent, Equatable, Sendable {
    public let eventId = "S8aUpSP9W"
    public let eventHash = "e631bb7feb22d57b78721ad34dd1e630d95b8f0515494c0a38226c7eb7a2c22e"

    public init(requiredStringEventProperty: AvoTypes.RequiredStringEventProperty,
            optionalStringEventProperty: AvoTypes.OptionalStringEventProperty?,
            requiredFloatEventProperty: Double,
            optionalFloatEventProperty: Double?,
            requiredBoolEventProperty: Bool,
            optionalBoolEventProperty: Bool?,
            requiredObjectEventProperty: AvoTypes.RequiredObjectEventProperty,
            optionalObjectEventProperty: AvoTypes.OptionalObjectEventProperty?,
            requiredListEventProperty: [AvoTypes.RequiredListEventProperty],
            optionalListEventProperty: [Int]?,
            requiredIntEventProperty: Int,
            optionalIntEventProperty: Int?) {
        self.requiredStringEventProperty = requiredStringEventProperty
        self.optionalStringEventProperty = optionalStringEventProperty
        self.requiredFloatEventProperty = requiredFloatEventProperty
        self.optionalFloatEventProperty = optionalFloatEventProperty
        self.requiredBoolEventProperty = requiredBoolEventProperty
        self.optionalBoolEventProperty = optionalBoolEventProperty
        self.requiredObjectEventProperty = requiredObjectEventProperty
        self.optionalObjectEventProperty = optionalObjectEventProperty
        self.requiredListEventProperty = requiredListEventProperty
        self.optionalListEventProperty = optionalListEventProperty
        self.requiredIntEventProperty = requiredIntEventProperty
        self.optionalIntEventProperty = optionalIntEventProperty
    }

    let requiredStringEventProperty: AvoTypes.RequiredStringEventProperty
    let optionalStringEventProperty: AvoTypes.OptionalStringEventProperty?
    let requiredFloatEventProperty: Double
    let optionalFloatEventProperty: Double?
    let requiredBoolEventProperty: Bool
    let optionalBoolEventProperty: Bool?
    let requiredObjectEventProperty: AvoTypes.RequiredObjectEventProperty
    let optionalObjectEventProperty: AvoTypes.OptionalObjectEventProperty?
    let requiredListEventProperty: [AvoTypes.RequiredListEventProperty]
    let optionalListEventProperty: [Int]?
    let requiredIntEventProperty: Int
    let optionalIntEventProperty: Int?

    // FEATURE REQUEST: "Typed Codegen Data Structures" [BLOCKER]
    // Instead of the old callback approach where Avo internally called
    // segmentDestination.logEvent("Test Event With Many Event Props", eventProperties),
    // the event now exposes its per-destination data as a typed dictionary.
    // The caller decides what to do with it.
    //
    // FEATURE REQUEST: "Systematized Universal Properties" [Must Have]
    // System properties are included here from AppSystemProperties.shared,
    // ensuring every event carries the app's system properties.
    public var properties: [String: AvoEventOut] {
        var eventProperties: [String: Any] = [:]
        eventProperties["Required String Event Property"] = requiredStringEventProperty.rawValue
        if let optionalStringEventProperty = optionalStringEventProperty {
            eventProperties["Optional String Event Property"] = optionalStringEventProperty.rawValue
        }
        eventProperties["Required Float Event Property"] = requiredFloatEventProperty
        if let optionalFloatEventProperty = optionalFloatEventProperty {
            eventProperties["Optional Float Event Property"] = optionalFloatEventProperty
        }
        eventProperties["Required Bool Event Property"] = requiredBoolEventProperty
        if let optionalBoolEventProperty = optionalBoolEventProperty {
            eventProperties["Optional Bool Event Property"] = optionalBoolEventProperty
        }
        eventProperties["Required Object Event Property"] = requiredObjectEventProperty.serialize()
        if let optionalObjectEventProperty = optionalObjectEventProperty {
            eventProperties["Optional Object Event Property"] = optionalObjectEventProperty.serialize()
        }
        eventProperties["Required List Event Property"] = requiredListEventProperty.map({ $0.rawValue })
        if let optionalListEventProperty = optionalListEventProperty {
            eventProperties["Optional List Event Property"] = optionalListEventProperty
        }
        eventProperties["Required Int Event Property"] = requiredIntEventProperty
        if let optionalIntEventProperty = optionalIntEventProperty {
            eventProperties["Optional Int Event Property"] = optionalIntEventProperty
        }

        // Merge system properties — app-specific, set at startup
        for (key, value) in AppSystemProperties.shared.toDictionary() {
            eventProperties[key] = value
        }

        return [
            "analyticsDest": AvoEventOut(name: "Test Event With Many Event Props", properties: eventProperties)
        ]
    }

    // FEATURE REQUEST: "Event Verify Method in Codegen" [Must Have]
    // verify() accumulates ALL violations — does not short-circuit on first failure.
    // This lets the caller see every problem at once, improving the debugging UX.
    public func verify() throws {
        var messages: [AvoAssertMessage] = []
        messages += AvoAssert.assertMax("requiredFloatEventProperty", "Required Float Event Property", max: 100.0, value: requiredFloatEventProperty)
        messages += AvoAssert.assertMin("requiredFloatEventProperty", "Required Float Event Property", min: 0.0, value: requiredFloatEventProperty)
        messages += AvoAssert.assertMax("requiredIntEventProperty", "Required Int Event Property", max: 1000, value: requiredIntEventProperty)
        messages += AvoAssert.assertMin("requiredIntEventProperty", "Required Int Event Property", min: 0, value: requiredIntEventProperty)

        if !messages.isEmpty {
            throw AvoVerificationError(messages: messages.map { $0.getMessage() })
        }
    }
}

// -----------------------------------------------------------------------
// Event: Test Empty Event
// Demonstrates an event with no custom properties (only system properties).
// -----------------------------------------------------------------------
public struct TestEmptyEventEvent: AvoEvent, Equatable, Sendable {
    public let eventId = "YEfSQR9HB"
    public let eventHash = "396b155dd744d2e121198d194a647c803fdd3a8ed51de8ed6eb25f7933d1cccb"

    public init() {}

    public var properties: [String: AvoEventOut] {
        // No event-specific properties — but system properties are still included
        var eventProperties: [String: Any] = [:]
        for (key, value) in AppSystemProperties.shared.toDictionary() {
            eventProperties[key] = value
        }
        return [
            "analyticsDest": AvoEventOut(name: "Test Empty Event", properties: eventProperties)
        ]
    }

    // No constraints to verify — returns without throwing
    public func verify() throws {
        // No-op: event has no properties with validation constraints
    }
}

// -----------------------------------------------------------------------
// Event: Test Name Mapping
// Demonstrates per-destination name mapping (enrichment at the app level).
//
// FEATURE REQUEST: "Automated JSON Key Formatting" [Must Have]
// This event shows how name mapping works in the new model:
// - The developer provides properties with their logical Swift names
// - The `properties` getter maps them to the correct JSON keys per destination
// - Global mappings apply to all destinations
// - Local mappings apply to specific destinations only
//
// Source: Avo.swift lines 660-686 (original struct) + lines 2758-2893 (original track method)
// In the original codegen, name mapping happened inside the Avo actor's track method.
// Now it happens in the event struct's properties getter — same logic, different location.
// -----------------------------------------------------------------------
public struct TestNameMappingEvent: AvoEvent, Equatable, Sendable {
    public let eventId = "TQcvIAPEA"
    public let eventHash = "482b4537ff9925833971ea45b91e95302ad5fca8a834aa37d7385c0258f084c7"

    public init(userId_: String,
            requiredStringEventPropertyWithNameMapping: String,
            optionalIntEventPropertyWithNameMapping: Int?,
            requiredFloatEventPropertyWithNameMapping: Double,
            optionalBoolEventPropertyWithNameMapping: Bool?,
            optionalListPropertyWithNameMapping: [String]?,
            requiredStringUserPropertyWithNameMapping: String) {
        self.userId_ = userId_
        self.requiredStringEventPropertyWithNameMapping = requiredStringEventPropertyWithNameMapping
        self.optionalIntEventPropertyWithNameMapping = optionalIntEventPropertyWithNameMapping
        self.requiredFloatEventPropertyWithNameMapping = requiredFloatEventPropertyWithNameMapping
        self.optionalBoolEventPropertyWithNameMapping = optionalBoolEventPropertyWithNameMapping
        self.optionalListPropertyWithNameMapping = optionalListPropertyWithNameMapping
        self.requiredStringUserPropertyWithNameMapping = requiredStringUserPropertyWithNameMapping
    }

    let userId_: String
    let requiredStringEventPropertyWithNameMapping: String
    let optionalIntEventPropertyWithNameMapping: Int?
    let requiredFloatEventPropertyWithNameMapping: Double
    let optionalBoolEventPropertyWithNameMapping: Bool?
    let optionalListPropertyWithNameMapping: [String]?
    let requiredStringUserPropertyWithNameMapping: String

    public var properties: [String: AvoEventOut] {
        var eventProperties: [String: Any] = [:]
        eventProperties["Required String Event Property with Name Mapping"] = requiredStringEventPropertyWithNameMapping
        if let optionalIntEventPropertyWithNameMapping = optionalIntEventPropertyWithNameMapping {
            eventProperties["Optional Int Event Property with Name Mapping"] = optionalIntEventPropertyWithNameMapping
        }
        eventProperties["Required Float Event Property with Name Mapping"] = requiredFloatEventPropertyWithNameMapping
        if let optionalBoolEventPropertyWithNameMapping = optionalBoolEventPropertyWithNameMapping {
            eventProperties["Optional Bool Event Property With Name Mapping"] = optionalBoolEventPropertyWithNameMapping
        }
        if let optionalListPropertyWithNameMapping = optionalListPropertyWithNameMapping {
            eventProperties["Optional List Property With Name Mapping"] = optionalListPropertyWithNameMapping
        }

        // Merge system properties
        for (key, value) in AppSystemProperties.shared.toDictionary() {
            eventProperties[key] = value
        }

        return [
            "analyticsDest": AvoEventOut(name: "Test Name Mapping", properties: eventProperties)
            // If there were more destinations with different name mappings:
            // "segment": AvoEventOut(name: "Test Name Mapping", properties: segmentEventProperties),
            // "amplitude": AvoEventOut(name: "Test Name Mapping", properties: amplitudeEventProperties),
        ]
    }

    public func verify() throws {
        // No min/max constraints on these properties — validation is purely type-based
    }
}

// -----------------------------------------------------------------------
// Event: Test All Types of Name Mapping
// Demonstrates global, per-destination, and local name mapping in one event.
//
// FEATURE REQUEST: "Automated JSON Key Formatting" [Must Have]
// Shows all name mapping variants:
// - Global all destinations: "GLOBAL_NAME_MAPPING_ALL" replaces original key everywhere
// - Global one destination: "GLOBAL_NAME_MAPPING_ONE" only for analyticsDest
// - Local all destinations: "LOCAL_NAME_MAPPING_ALL" replaces original key everywhere
// - Local one destination: "LOCAL_NAME_MAPPING_ONE" only for analyticsDest
// - Event name mapping: analyticsDest gets "EVENT_NAME_MAPPING" instead of "Test All Types of Name Mapping"
//
// Source: Avo.swift lines 763-795 (struct) + lines 3444-3593 (track method)
// -----------------------------------------------------------------------
public struct TestAllTypesOfNameMappingEvent: AvoEvent, Equatable, Sendable {
    public let eventId = "BOPQbqkmFN"
    public let eventHash = "fbcabba203a9d5dac2ea22ecf64c010c111bfddcfed0e1d3d0320c4a07b5946a"

    public init(userId_: String,
            eventPropertyWithGlobalNameMappingAllDestinations: String,
            eventPropertyWithGlobalNameMappingOneDestinationn: String,
            eventPropertyWithLocalNameMappingOneDestination: String,
            eventPropertyWithLocalNameMappingAllDestinations: String,
            userPropertyWithGlobalNameMappingAllDestinations: String,
            userPropertyWithGlobalNameMappingOneDestination: String,
            userPropertyWithLocalNameMappingAllDestinations: String,
            userPropertyWithLocalNameMappingOneDestination: String) {
        self.userId_ = userId_
        self.eventPropertyWithGlobalNameMappingAllDestinations = eventPropertyWithGlobalNameMappingAllDestinations
        self.eventPropertyWithGlobalNameMappingOneDestinationn = eventPropertyWithGlobalNameMappingOneDestinationn
        self.eventPropertyWithLocalNameMappingOneDestination = eventPropertyWithLocalNameMappingOneDestination
        self.eventPropertyWithLocalNameMappingAllDestinations = eventPropertyWithLocalNameMappingAllDestinations
        self.userPropertyWithGlobalNameMappingAllDestinations = userPropertyWithGlobalNameMappingAllDestinations
        self.userPropertyWithGlobalNameMappingOneDestination = userPropertyWithGlobalNameMappingOneDestination
        self.userPropertyWithLocalNameMappingAllDestinations = userPropertyWithLocalNameMappingAllDestinations
        self.userPropertyWithLocalNameMappingOneDestination = userPropertyWithLocalNameMappingOneDestination
    }

    let userId_: String
    let eventPropertyWithGlobalNameMappingAllDestinations: String
    let eventPropertyWithGlobalNameMappingOneDestinationn: String
    let eventPropertyWithLocalNameMappingOneDestination: String
    let eventPropertyWithLocalNameMappingAllDestinations: String
    let userPropertyWithGlobalNameMappingAllDestinations: String
    let userPropertyWithGlobalNameMappingOneDestination: String
    let userPropertyWithLocalNameMappingAllDestinations: String
    let userPropertyWithLocalNameMappingOneDestination: String

    public var properties: [String: AvoEventOut] {
        var customDestEventProperties: [String: Any] = [:]
        // Global name mapping — all destinations
        customDestEventProperties["GLOBAL_NAME_MAPPING_ALL"] = eventPropertyWithGlobalNameMappingAllDestinations
        // Global name mapping — only this destination gets the renamed key
        customDestEventProperties["GLOBAL_NAME_MAPPING_ONE"] = eventPropertyWithGlobalNameMappingOneDestinationn
        // Local name mapping — only this destination gets the renamed key
        customDestEventProperties["LOCAL_NAME_MAPPING_ONE"] = eventPropertyWithLocalNameMappingOneDestination
        // Local name mapping — all destinations
        customDestEventProperties["LOCAL_NAME_MAPPING_ALL"] = eventPropertyWithLocalNameMappingAllDestinations

        // Merge system properties
        for (key, value) in AppSystemProperties.shared.toDictionary() {
            customDestEventProperties[key] = value
        }

        // Event name is also mapped for analyticsDest: "EVENT_NAME_MAPPING"
        // Other destinations would use "Test All Types of Name Mapping"
        return [
            "analyticsDest": AvoEventOut(name: "EVENT_NAME_MAPPING", properties: customDestEventProperties)
            // Other destinations would have different property key mappings:
            // "segment": AvoEventOut(name: "Test All Types of Name Mapping", properties: [
            //     "GLOBAL_NAME_MAPPING_ALL": eventPropertyWithGlobalNameMappingAllDestinations,
            //     "Event Property With Global Name Mapping One Destinationn": eventPropertyWithGlobalNameMappingOneDestinationn,
            //     "Event Property With Local Name Mapping One Destination": eventPropertyWithLocalNameMappingOneDestination,
            //     "LOCAL_NAME_MAPPING_ALL": eventPropertyWithLocalNameMappingAllDestinations,
            // ]),
        ]
    }

    public func verify() throws {
        // No min/max constraints on string properties
    }
}

// -----------------------------------------------------------------------
// Event: Test Pinned Properties
// Demonstrates pinned properties — constant values set at generation time,
// not provided by the developer.
//
// Source: Avo.swift lines 808-814 (struct) + lines 3830-3929 (track method)
// Notice: The developer only passes userId_, but the event includes
// "Pinned String Property", "Pinned Int Property", and "Pinned Bool Property"
// which are set to constant values in the properties getter.
// -----------------------------------------------------------------------
public struct TestPinnedPropertiesEvent: AvoEvent, Equatable, Sendable {
    public let eventId = "D6AIPQzd3f"
    public let eventHash = "202d7e3c5e74d7443c0ee6605a1659b7379306251fa0f9902c8bc0b7f26d8d6a"

    public init(userId_: String) {
        self.userId_ = userId_
    }

    let userId_: String

    public var properties: [String: AvoEventOut] {
        var eventProperties: [String: Any] = [:]
        // Pinned properties — these values are set in the Avo workspace,
        // not provided by the developer at the call site.
        // The developer only needs to provide userId_.
        eventProperties["Pinned String Property"] = "Pinned String"
        eventProperties["Pinned Int Property"] = 42
        eventProperties["Pinned Bool Property"] = true

        // Merge system properties
        for (key, value) in AppSystemProperties.shared.toDictionary() {
            eventProperties[key] = value
        }

        return [
            "analyticsDest": AvoEventOut(name: "Test Pinned Properties", properties: eventProperties)
        ]
    }

    public func verify() throws {
        // Pinned properties have fixed values — nothing to validate
    }
}

// -----------------------------------------------------------------------
// Event: Event With Allowed Values
// Demonstrates how Avo governs allowed values at compile time via enums.
//
// The developer CANNOT pass an arbitrary string — they must pick from the
// enum cases defined in AvoTypes. The compiler rejects invalid values.
// This is how "allowed values" configured in the Avo workspace translate
// to type-safe code in the generated output.
//
// There is also a VARIANT of this event (EventWithAllowedValuesVariantIEvent)
// that uses a different set of allowed values for the same logical property.
// Variants let teams customize events for different contexts while still
// governing each variant's allowed values independently.
//
// Source: Avo.swift lines 1014-1027, AvoProtocol.swift lines 90-95
// -----------------------------------------------------------------------
public struct EventWithAllowedValuesEvent: AvoEvent, Equatable, Sendable {
    public let eventId = "dfuLieo-Mx"
    public let eventHash = "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"

    public init(eventPropertyWithAllowedValues: AvoTypes.EventPropertyWithAllowedValues) {
        self.eventPropertyWithAllowedValues = eventPropertyWithAllowedValues
    }

    let eventPropertyWithAllowedValues: AvoTypes.EventPropertyWithAllowedValues

    public var properties: [String: AvoEventOut] {
        var eventProperties: [String: Any] = [:]
        eventProperties["Event Property With Allowed Values"] = eventPropertyWithAllowedValues.rawValue

        // Merge system properties
        for (key, value) in AppSystemProperties.shared.toDictionary() {
            eventProperties[key] = value
        }

        return [
            "analyticsDest": AvoEventOut(name: "Event With Allowed Values", properties: eventProperties)
        ]
    }

    public func verify() throws {
        // No runtime validation needed — the enum type enforces allowed values at compile time.
        // Passing an invalid value is a compile error, not a runtime error.
    }
}

// Variant of the same event with a DIFFERENT set of allowed values.
// "Value II" is not allowed here, but "Variant Value I" is.
public struct EventWithAllowedValuesVariantIEvent: AvoEvent, Equatable, Sendable {
    public let eventId = "dfuLieo-Mx-varI"
    public let eventHash = "b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3"

    public init(eventPropertyWithAllowedValues: AvoTypes.EventPropertyWithAllowedValuesVariantI) {
        self.eventPropertyWithAllowedValues = eventPropertyWithAllowedValues
    }

    let eventPropertyWithAllowedValues: AvoTypes.EventPropertyWithAllowedValuesVariantI

    public var properties: [String: AvoEventOut] {
        var eventProperties: [String: Any] = [:]
        eventProperties["Event Property With Allowed Values"] = eventPropertyWithAllowedValues.rawValue

        // Merge system properties
        for (key, value) in AppSystemProperties.shared.toDictionary() {
            eventProperties[key] = value
        }

        return [
            "analyticsDest": AvoEventOut(name: "Event With Allowed Values", properties: eventProperties)
        ]
    }

    public func verify() throws {
        // No runtime validation needed — the enum type enforces allowed values at compile time.
    }
}
