// swiftlint:disable all
// Generated by Avo VERSION 222.0.0. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.

// ============================================================================
// LIBRARY LAYER — Shared across all apps
// ============================================================================
// This file lives in the shared analytics library. It contains:
// - AvoEvent protocol and AvoEventOut type (the API contract)
// - AvoAssert (validation primitives)
// - Avo actor (optional shared infrastructure)
// - AvoInvoke (implementation status reporting stub)
//
// NOTE: AvoTypes (enums, object structs) are app-specific and live in AppEvents.swift.
// Each app has its own event schemas with different allowed values and property types.
//
// FEATURE REQUEST: "Avo Library for Common Types" [BLOCKER]
// This file IS the solution to that request. By placing the AvoEvent protocol,
// AvoEventOut, and AvoTypes in a shared library, any app can define its own
// event structs conforming to AvoEvent, while the library provides the common
// "currency types" for integration. The library has zero knowledge of
// app-specific events.
//
// FEATURE REQUEST: "Typed Codegen Data Structures" [BLOCKER]
// The old approach used global callback-based routing (AvoCustomDestination protocol
// with make/logEvent/setUserProperties callbacks configured at init time).
// This new approach generates well-defined, typed data structures per event (structs
// in the App layer) that conform to the AvoEvent protocol. Each struct exposes
// typed properties and a verify() method — no callbacks needed at the event level.
// The developer creates a struct, calls verify(), reads .properties, and passes
// the data to their own analytics library.
//
// FEATURE REQUEST: "Event Verify Method in Codegen" [Must Have]
// The AvoEvent protocol below includes `func verify() throws`. Each generated
// event struct implements this method with its specific validation rules (min/max
// assertions). The verify() method is pure — it throws AvoVerificationError on
// failure with accumulated violation messages. No side effects, no env guards.
// This enables:
// - Internal library use: call verify() before sending to catch bad data
// - Reporting: catch the error and route to your own reporting infra
// - Unit testing: assert that verify() throws/doesn't throw for given inputs
//
// FEATURE REQUEST: "Automated JSON Key Formatting" [Must Have]
// Name mapping is handled in the event struct's `properties` computed property.
// Each destination can have different key names for the same logical property.
// The codegen generates the correct key names per destination based on the
// workspace configuration. See AppEvents.swift for examples of:
// - Global name mapping (all destinations get a renamed key)
// - Per-destination name mapping (only specific destinations get renamed keys)
// - snake_case formatting applied at generation time
//
// FEATURE REQUEST: "TypeScript Tracking Objects" [Must Have]
// While this demo is Swift, the same architectural pattern applies to TypeScript.
// Instead of callback-based routing, TS codegen would return typed tracking objects
// with name + properties. The AvoEventOut equivalent in TS would be:
//   interface AvoEventOut { name: string; properties: Record<string, unknown> }
// And each event function would return Record<string, AvoEventOut> keyed by destination.
//
// ALTERNATIVE CONFIGURATION: If this library layer is too heavy for your use case,
// you can strip it down to just the protocol + types (remove the Avo actor entirely).
// See the "WITHOUT AVO INSTANCE" comments in App/AppUsage.swift for what changes.
// ============================================================================

import Foundation

// MARK: - Protocol Types

public enum AvoEnv {
    case prod
    case staging
    case dev
}

// FEATURE REQUEST: "Typed Codegen Data Structures" [BLOCKER]
// AvoEventOut is the typed output structure that replaces the old callback approach.
// Instead of: customDest.logEvent(eventName: "...", eventProperties: [...])
// You now get: let out = event.properties["analyticsDest"] → AvoEventOut(name: "...", properties: [...])
// The caller decides what to do with the typed data.
public struct AvoEventOut: @unchecked Sendable {
    // @unchecked Sendable because [String: Any] is not Sendable under strict concurrency,
    // matching the pattern used for SegmentDestination et al. in the original codegen.
    public let name: String
    public let properties: [String: Any]

    public init(name: String, properties: [String: Any]) {
        self.name = name
        self.properties = properties
    }
}

/// Errors thrown by AvoEvent.verify() implementations.
/// Contains all accumulated violation messages — verify() does NOT short-circuit on the first failure.
public struct AvoVerificationError: Error {
    public let messages: [String]

    public init(messages: [String]) {
        self.messages = messages
    }
}

// FEATURE REQUEST: "Avo Library for Common Types" [BLOCKER]
// FEATURE REQUEST: "Event Verify Method in Codegen" [Must Have]
// This protocol is the core "currency type" that the shared library exposes.
// App-specific event structs conform to this protocol.
// The library can work with any AvoEvent without knowing the concrete type.
/// This is a public protocol that should be conformed by Avo generated event structs in the app layer.
public protocol AvoEvent: Sendable {
    /// Returns per-destination enriched properties.
    /// Keys are destination identifiers (e.g., "analyticsDest", "segment").
    /// Values are AvoEventOut containing the destination-specific event name and properties
    /// (with name mapping, pinned properties, and system properties applied).
    ///
    /// Note: System properties are included by the app-level event struct directly,
    /// since different apps can have different system properties.
    ///
    /// FEATURE REQUEST: "Automated JSON Key Formatting" [Must Have]
    /// The properties dictionary contains keys already formatted per the workspace configuration.
    /// Name mapping (global, per-destination, local) is applied at generation time in each
    /// event struct's implementation of this property.
    var properties: [String: AvoEventOut] { get }

    /// The Avo event ID — a unique identifier for this event type, generated by Avo.
    /// Used for implementation status reporting (AvoInvoke) and inspector integration.
    var eventId: String { get }

    /// The Avo event hash — a content hash of the event schema, generated by Avo.
    /// Used for implementation status reporting (AvoInvoke).
    var eventHash: String { get }

    /// Validates the event's properties against schema constraints.
    /// Throws AvoVerificationError if any validation fails.
    /// Pure function — no side effects, no env guards, no reporting.
    ///
    /// FEATURE REQUEST: "Event Verify Method in Codegen" [Must Have]
    /// This method enables:
    /// - Library-level validation before sending
    /// - Integration with custom error reporting infrastructure
    /// - Unit testing of event schemas
    func verify() throws
}

// NOTE: AvoTypes (enums, object structs) are APP-SPECIFIC — each app has its own
// event schemas with their own allowed values, property types, and system properties.
// They live in AppEvents.swift alongside the event structs, not in this shared library.
// The library only provides the protocol contract (AvoEvent, AvoEventOut) and infrastructure.

// MARK: - Infrastructure

// FEATURE REQUEST: "Event Verify Method in Codegen" [Must Have]
// AvoAssert provides the validation primitives used by verify() implementations.
// Both AvoAssert and AvoAssertMessage are `internal` (not `private`) so that
// app-layer event structs can call AvoAssert.assertMin/assertMax and accumulate
// AvoAssertMessage values in their verify() implementations.
enum AvoAssertMessage {
    case expectedMax(propertyId: String, message: String)
    case expectedMin(propertyId: String, message: String)

    func getMessage() -> String {
        switch self {
        case .expectedMax(_, let message):
            return message
        case .expectedMin(_, let message):
            return message
        }
    }
}

struct AvoAssert {
    private init() {}

    static func assertMax(_ propertyId: String, _ propertyName: String, max: Double, value: Double) -> [AvoAssertMessage] {
        if (value > max) {
            return [AvoAssertMessage.expectedMax(propertyId: propertyId, message: "\(propertyName) has a maximum value of \(String(max)) but you provided the value \(String(value))")]
        } else {
            return []
        }
    }

    static func assertMax(_ propertyId: String, _ propertyName: String, max: Int, value: Int) -> [AvoAssertMessage] {
        if (value > max) {
            return [AvoAssertMessage.expectedMax(propertyId: propertyId, message: "\(propertyName) has a maximum value of \(String(max)) but you provided the value \(String(value))")]
        } else {
            return []
        }
    }

    static func assertMin(_ propertyId: String, _ propertyName: String, min: Double, value: Double) -> [AvoAssertMessage] {
        if (value < min) {
            return [AvoAssertMessage.expectedMin(propertyId: propertyId, message: "\(propertyName) has a minimum value of \(String(min)) but you provided the value \(String(value))")]
        } else {
            return []
        }
    }

    static func assertMin(_ propertyId: String, _ propertyName: String, min: Int, value: Int) -> [AvoAssertMessage] {
        if (value < min) {
            return [AvoAssertMessage.expectedMin(propertyId: propertyId, message: "\(propertyName) has a minimum value of \(String(min)) but you provided the value \(String(value))")]
        } else {
            return []
        }
    }
}

/// Implementation status reporting stub.
/// In production codegen, this posts to https://api.avo.app/i with account ID, schema ID,
/// branch, and source fields to report event implementation status.
/// In this demo, it is a no-op — no network calls are made.
private struct AvoInvoke {
    private init() {}

    static func invoke(_ eventId: String, _ hash: String, _ messages: [AvoAssertMessage]) {
        // NO-OP STUB: In production codegen, this would POST to https://api.avo.app/i
        // with payload containing: ac (account ID), br (branch), en (env), ev (eventId),
        // ha (hash), sc (schema ID), se (timestamp), so (source ID), va (valid), me (messages).
        // SamplingRateManager is omitted because it only supports the live network call path.
    }

    static func invokeMeta(_ type: String, _ messages: [AvoAssertMessage]) {
        // NO-OP STUB: In production codegen, this would POST initialization metadata
        // to https://api.avo.app/i for implementation status tracking.
    }
}

// MARK: - Avo Actor

// FEATURE REQUEST: "Avo Library for Common Types" [BLOCKER]
// The Avo actor is OPTIONAL. It provides shared infrastructure:
// - Environment (dev/staging/prod)
// - Strict mode flag (stored but not enforced in this demo)
// - Noop mode (skips sending)
// - Inspector integration
// - Implementation status reporting (AvoInvoke)
//
// The library receives events from the app, reads their properties, verifies
// them if needed, and returns enriched event data to the caller for forwarding.
//
// System properties are APP-SPECIFIC (different apps can have different system
// properties), so they live in the app layer — each event struct includes them
// in its `properties` getter. The Avo actor does NOT store or merge system properties.
//
// WITHOUT THE AVO INSTANCE:
// - No environment gating (all code paths run)
// - No inspector integration
// - No AvoInvoke implementation-status reporting
// - No noop mode
// - No strict mode flag
// The AvoEvent protocol and AvoEventOut still work standalone — the app just
// calls event.verify() and event.properties directly.
public actor Avo {
    var __STRICT__: Bool = true
    // __STRICT__ is a named concept only in this demo.
    // Its presence here demonstrates that the variable exists for future use and
    // is absent in the no-instance path.

    public private(set) var __ENV__: AvoEnv = .prod
    public private(set) var __NOOP__: Bool = false
    var __INSPECTOR__: AnyObject?

    private init() {}

    private func configure(
        env: AvoEnv,
        inspector: AnyObject? = nil,
        strict: Bool = true,
        noop: Bool = false
    ) {
        __ENV__ = env
        __NOOP__ = noop
        __STRICT__ = strict

        // Note: In production codegen, logging will be configurable via a custom logger
        // (e.g., AvoLogger protocol with logDebug/logWarn/logError). For this demo, NSLog is used directly.
        if noop && env == .prod {
            NSLog("[avo] WARNING: Avo cannot be initialized in noop mode in production. Overwriting with noop=false.")
            __NOOP__ = false
        }
        if __NOOP__ {
            NSLog("[avo] Avo is now initialized in noop mode. No events will be sent.")
        }

        // Inspector setup
        if !__NOOP__ {
            self.__INSPECTOR__ = inspector
            if inspector != nil {
                let initSelector = Selector(("initWithApiKey:envInt:"))
                if (self.__INSPECTOR__?.responds(to: initSelector)) == true {
                    if __ENV__ == .prod {
                        let _ = self.__INSPECTOR__?.perform(initSelector, with:"YOUR_INSPECTOR_API_KEY", with:0) // Replace with your real key from the AvoInspector dashboard
                    } else if __ENV__ == .staging {
                        let _ = self.__INSPECTOR__?.perform(initSelector, with:"YOUR_INSPECTOR_API_KEY", with:2) // Replace with your real key from the AvoInspector dashboard
                    } else {
                        let _ = self.__INSPECTOR__?.perform(initSelector, with:"YOUR_INSPECTOR_API_KEY", with:1) // Replace with your real key from the AvoInspector dashboard
                    }
                }
            }
        }

        // Implementation status reporting (no-op stub in demo)
        if __ENV__ != .prod {
            AvoInvoke.invokeMeta("init", [])
        }
    }

    /// Factory method to create and configure an Avo instance.
    ///
    /// - Parameters:
    ///   - env: The environment (dev/staging/prod)
    ///   - inspector: Optional AvoInspector instance (pass nil to disable)
    ///   - strict: Stored but not enforced in this demo
    ///   - noop: When true, send() is a no-op
    public static func initAvo(
        env: AvoEnv,
        inspector: AnyObject? = nil,
        strict: Bool = true,
        noop: Bool = false
    ) async -> Avo {
        let avo = Avo()
        await avo.configure(
            env: env,
            inspector: inspector,
            strict: strict,
            noop: noop
        )
        return avo
    }

    /// Processes an event: verifies, reports to inspector, and returns per-destination enriched data.
    ///
    /// 1. Calls `event.verify()` — throws `AvoVerificationError` if validation fails
    /// 2. Reads the event's per-destination properties
    ///    (system properties are already included by the app-level event struct)
    /// 3. Reports to inspector (automatic path) if configured
    /// 4. Returns the per-destination dictionary so the caller can forward each entry to the appropriate backend
    ///
    /// - Throws: `AvoVerificationError` if the event fails schema validation.
    /// - Returns: `[String: AvoEventOut]` — per-destination enriched data. Empty if noop mode is active.
    public func process(event: AvoEvent) throws -> [String: AvoEventOut] {
        // Guard on noop
        if __NOOP__ {
            return [:]
        }

        // Verify the event — throws AvoVerificationError if validation fails
        try event.verify()

        // Report implementation status to Avo servers (no-op stub in this demo).
        // In production codegen, this POSTs to api.avo.app/i with the event's ID, hash,
        // and validation results — enabling implementation status tracking in the Avo workspace.
        if __ENV__ != .prod {
            AvoInvoke.invoke(event.eventId, event.eventHash, [])
        }

        let eventProperties = event.properties

        // Guard on empty properties
        if eventProperties.isEmpty {
            NSLog("[avo] Warning: Event has no destination properties, skipping")
            return [:]
        }

        // INSPECTOR — Automatic path: inspector is called from inside the process flow.
        // This is one of two inspector integration patterns shown in this demo.
        // See AppUsage.swift for the manual path (sendToInspector called explicitly).
        if self.__INSPECTOR__ != nil {
            let trackSchemaFromEventSelector = Selector(("avoFunctionTrackSchemaFromEvent:eventParams:"))
            if self.__INSPECTOR__?.responds(to: trackSchemaFromEventSelector) == true {
                if let firstEvent = eventProperties.values.first {
                    var inspectorProperties = firstEvent.properties
                    inspectorProperties["avoFunctionEventId"] = event.eventId
                    inspectorProperties["avoFunctionEventHash"] = event.eventHash
                    let _ = self.__INSPECTOR__?.perform(trackSchemaFromEventSelector, with: firstEvent.name, with: inspectorProperties)
                }
            }
        }

        // Return all per-destination event data — the caller forwards each to the appropriate backend
        return eventProperties
    }

    /// Reports an event to inspector manually — the second inspector integration pattern.
    /// Call this from your library code when YOU decide to report to inspector,
    /// rather than having it happen automatically inside process().
    ///
    /// This method does NOT verify the event or return event data.
    /// If inspector is nil, this is a no-op.
    ///
    /// Note: avoFunctionEventId and avoFunctionEventHash are omitted because
    /// AvoEvent protocol has no eventId/eventHash fields.
    public func sendToInspector(event: AvoEvent) {
        guard let inspector = self.__INSPECTOR__ else { return }

        guard let avoEventOut = event.properties["analyticsDest"] else { return }

        let trackSchemaFromEventSelector = Selector(("avoFunctionTrackSchemaFromEvent:eventParams:"))
        if inspector.responds(to: trackSchemaFromEventSelector) == true {
            let _ = inspector.perform(trackSchemaFromEventSelector, with: avoEventOut.name, with: avoEventOut.properties)
        }
    }
}
