// Generated by Avo. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.
//
// App A's source-specific file: events, enums, system properties, and config
// generated from App A's Avo source. The shared runtime types (AvoEvent,
// AvoDestinationEvent, Avo, ...) come from the :library module (package sh.avo).
//
// NOTE: this example plan was generated into package `com.avodemo.appa.avo`
// (instead of the default `sh.avo`) so a shell app can depend on both App A's
// and App B's generated code without class name collisions.
@file:Suppress("unused", "LiftReturnOrAssignment", "FunctionName", "UnusedImport",
"ObjectPropertyName", "SameParameterValue", "UnnecessaryVariable", "UNUSED_PARAMETER",
"UNUSED_VARIABLE", "LocalVariableName", "DEPRECATION", "UsePropertyAccessSyntax",
"PrivatePropertyName", "PrivatePropertyName", "CascadeIf", "MemberVisibilityCanBePrivate",
"SpellCheckingInspection", "EnumEntryName", "MaximumLineLength")
package com.avodemo.appa.avo

import sh.avo.*

object AvoTypes {
    enum class Client(val underlying: String) {
        WEB("Web"),
        I_O_S("iOS"),
        ANDROID("Android")
    }
}

object AppSystemProperties {
    @Volatile private var _configured = false
    val isConfigured: Boolean
        @Synchronized get() {
        return _configured
    }

    private var _client: AvoTypes.Client? = null
    private var _appVersion: String? = null
    private var _sessionCount: Int? = null

    @Synchronized fun configure(
        client: AvoTypes.Client,
        appVersion: String,
        sessionCount: Int?
    ) {
        _client = client
        _appVersion = appVersion
        _sessionCount = sessionCount
        _configured = true
    }

    @Synchronized fun toMap(): Map<String, Any> {
        if (!_configured) {
            println("[avo] Warning: AppSystemProperties.configure() has not been called. System properties will be omitted.")
            return emptyMap()
        }
        val props = mutableMapOf<String, Any>()
        _client?.let {
            props["Client"] = it.underlying
        }
         ?: run {
            println("[avo] Warning: Required system property 'Client' was not set. Call AppSystemProperties.configure() with this property.")
        }
        _appVersion?.let {
            props["App Version"] = it
        }
         ?: run {
            println("[avo] Warning: Required system property 'App Version' was not set. Call AppSystemProperties.configure() with this property.")
        }
        _sessionCount?.let {
            props["Session Count"] = it
        }
        return props
    }

    @Synchronized fun collectViolations(): List<AvoAssertMessage> {
        val messages = mutableListOf<AvoAssertMessage>()
        _sessionCount?.let { sessionCount ->
            messages.addAll(AvoAssert.assertMin("qL3xVzA1a", "Session Count", min=0, value=sessionCount))
        }

        return messages
    }
}

object TestEmptyEventEvent : AvoEvent {
    override val eventId = "aAemptyEv"
    override val eventHash = "3f1a6c0d9b2e5f4a7c8d1e0b3a6f9c2d5e8b1a4f7c0d3e6b9a2f5c8d1e4b7a0f"
    override val eventName = "Test Empty Event"

    override fun buildBaseProperties(): Map<String, Any> {
        val eventProperties = mutableMapOf<String, Any>()

        for ((key, value) in AppSystemProperties.toMap()) {
            eventProperties[key] = value
        }
        return eventProperties
    }

    override val properties: Map<String, AvoDestinationEvent>
    get() {
        val eventProperties = buildBaseProperties()

        return mapOf(
            "segment" to AvoDestinationEvent(name = "Test Empty Event", properties = eventProperties),
            "amplitude" to AvoDestinationEvent(name = "Test Empty Event", properties = eventProperties),
            "mixpanel" to AvoDestinationEvent(name = "Test Empty Event", properties = eventProperties),
            "customDest" to AvoDestinationEvent(name = "Test Empty Event", properties = eventProperties)
        )
    }

    override fun collectViolations(): List<AvoAssertMessage> {
        val messages = mutableListOf<AvoAssertMessage>()
        messages.addAll(AppSystemProperties.collectViolations())

        return messages
    }

    override fun verify(): AvoResult<Unit, AvoVerificationError> {
        if (!AppSystemProperties.isConfigured) {
            return AvoResult.Failure(AvoVerificationError(listOf("AppSystemProperties.configure() must be called before sending events.")))
        }
        val violations = collectViolations()
        return if (violations.isEmpty()) {
            AvoResult.Success(Unit)
        } else {
            AvoResult.Failure(AvoVerificationError(violations.map { it.message }))
        }
    }
}

data class TestNameMappingEvent(val searchQuery: String,
    val resultCount: Int?) : AvoEvent {
    override val eventId = "aAnameMap"
    override val eventHash = "8c2e5b1f4a7d0c3e6b9f2a5d8c1e4b7f0a3d6c9e2b5f8a1d4c7e0b3f6a9d2c5e"
    override val eventName = "Test Name Mapping"

    override fun buildBaseProperties(): Map<String, Any> {
        val eventProperties = mutableMapOf<String, Any>()
        eventProperties["Search Query"] = searchQuery
        resultCount?.let {
            eventProperties["Result Count"] = it
        }

        for ((key, value) in AppSystemProperties.toMap()) {
            eventProperties[key] = value
        }
        return eventProperties
    }

    override val properties: Map<String, AvoDestinationEvent>
    get() {
        val eventProperties = buildBaseProperties()

        // Segment destination: event and property names remapped
        val segmentEventProperties = eventProperties.toMutableMap()
        segmentEventProperties.remove("Search Query")
        eventProperties["Search Query"]?.let { segmentEventProperties["query_text"] = it }

        return mapOf(
            "segment" to AvoDestinationEvent(name = "test_name_mapping", properties = segmentEventProperties),
            "amplitude" to AvoDestinationEvent(name = "Test Name Mapping", properties = eventProperties),
            "mixpanel" to AvoDestinationEvent(name = "Test Name Mapping", properties = eventProperties),
            "customDest" to AvoDestinationEvent(name = "Test Name Mapping", properties = eventProperties)
        )
    }

    override fun collectViolations(): List<AvoAssertMessage> {
        val messages = mutableListOf<AvoAssertMessage>()
        messages.addAll(AppSystemProperties.collectViolations())
        resultCount?.let { resultCount ->
            messages.addAll(AvoAssert.assertMin("qL3xVzA1b", "Result Count", min=0, value=resultCount))
        }

        return messages
    }

    override fun verify(): AvoResult<Unit, AvoVerificationError> {
        if (!AppSystemProperties.isConfigured) {
            return AvoResult.Failure(AvoVerificationError(listOf("AppSystemProperties.configure() must be called before sending events.")))
        }
        val violations = collectViolations()
        return if (violations.isEmpty()) {
            AvoResult.Success(Unit)
        } else {
            AvoResult.Failure(AvoVerificationError(violations.map { it.message }))
        }
    }
}

object AvoTrackingPlanConfig {
    val config = AvoInvokeConfig(
        actionId = "REPLACE_WITH_APP_A_ACTION_ID",
        branchId = "master",
        schemaId = "REPLACE_WITH_APP_A_SCHEMA_ID",
        sourceId = "REPLACE_WITH_APP_A_SOURCE_ID",
        inspectorApiKey = null
    )
}


fun Avo.Companion.initAvo(
    env: AvoEnv,
    client: AvoTypes.Client,
    appVersion: String,
    sessionCount: Int?,
    inspector: Any? = null,
    strict: Boolean = true,
    noop: Boolean = false
): Avo {
    AppSystemProperties.configure(
        client = client,
        appVersion = appVersion,
        sessionCount = sessionCount
    )
    return Avo(env = env, config = AvoTrackingPlanConfig.config, inspector = inspector, strict = strict, noop = noop)
}
